[project]
name = "2025-ytu-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.3.4",
    "mido>=1.3.3",
    "numpy>=2.2.1",
    "polars>=1.20.0",
]
